include_defs('//lib/maven.defs')

maven_jar(
  name = 'javamelody',
  id = 'net.bull.javamelody:javamelody-core:1.52.0',
  sha1 = '56a95e342f346a775887e7d0f6c302cd3cde014b',
  license = 'DO_NOT_DISTRIBUTE',
)

maven_jar(
  name = 'jrobin',
  id = 'org.jrobin:jrobin:1.5.9',
  sha1 = 'bd9a84484c67de930fa841f23cd6a93108b05cd0',
  license = 'DO_NOT_DISTRIBUTE',
)
