include_defs('//lib/maven.defs')

maven_jar(
  name = 'javamelody',
  id = 'net.bull.javamelody:javamelody-core:1.55.0',
  sha1 = '65c4f7cec7f499ac312e57704d3e37f39ee940ee',
  license = 'DO_NOT_DISTRIBUTE',
)

maven_jar(
  name = 'jrobin',
  id = 'org.jrobin:jrobin:1.5.9',
  sha1 = 'bd9a84484c67de930fa841f23cd6a93108b05cd0',
  license = 'DO_NOT_DISTRIBUTE',
)
