include_defs('//bucklets/maven_jar.bucklet')

VER = '2.12-rc0'
REPO = MAVEN_CENTRAL

maven_jar(
  name = 'api',
  id = 'com.google.gerrit:gerrit-extension-api:' + VER,
  sha1 = 'ee4deac28112cdb65dda69468572523ce359b3bb',
  license = 'Apache2.0',
  attach_source = False,
  repository = REPO,
)

