include_defs('//bucklets/maven_jar.bucklet')

VER = '2.11'
REPO = MAVEN_CENTRAL

maven_jar(
  name = 'api',
  id = 'com.google.gerrit:gerrit-extension-api:' + VER,
  sha1 = '2b327cf54db27263ad4593f29875b9ead6dbcc9a',
  license = 'Apache2.0',
  attach_source = False,
  repository = REPO,
)

